/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
// 10 / 03 / 2024
//Cristian Andres Monterrosa Durango
//Julian Esteban Monsalve Idarraga
package juegocartas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class FrmJuego extends javax.swing.JFrame {

    /**
     * Creates new form FrmJuego
     */
    Jugador jugador1 = new Jugador();
    Jugador jugador2 = new Jugador();

    public FrmJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRepartir = new javax.swing.JButton();
        btnVerificar = new javax.swing.JButton();
        tpJugadores = new javax.swing.JTabbedPane();
        pnlJugador1 = new javax.swing.JPanel();
        pnlJugador2 = new javax.swing.JPanel();
        btnConteo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apuntado");
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRepartir.setBackground(new java.awt.Color(51, 255, 51));
        btnRepartir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRepartir.setForeground(new java.awt.Color(0, 0, 0));
        btnRepartir.setText("Repartir");
        btnRepartir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepartirActionPerformed(evt);
            }
        });
        getContentPane().add(btnRepartir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        btnVerificar.setBackground(new java.awt.Color(102, 255, 51));
        btnVerificar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnVerificar.setForeground(new java.awt.Color(0, 0, 0));
        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        tpJugadores.setBackground(new java.awt.Color(204, 255, 255));
        tpJugadores.setForeground(new java.awt.Color(0, 0, 0));
        tpJugadores.setToolTipText("");

        pnlJugador1.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout pnlJugador1Layout = new javax.swing.GroupLayout(pnlJugador1);
        pnlJugador1.setLayout(pnlJugador1Layout);
        pnlJugador1Layout.setHorizontalGroup(
            pnlJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        pnlJugador1Layout.setVerticalGroup(
            pnlJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );

        tpJugadores.addTab("Cristian Durango", pnlJugador1);

        pnlJugador2.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout pnlJugador2Layout = new javax.swing.GroupLayout(pnlJugador2);
        pnlJugador2.setLayout(pnlJugador2Layout);
        pnlJugador2Layout.setHorizontalGroup(
            pnlJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        pnlJugador2Layout.setVerticalGroup(
            pnlJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );

        tpJugadores.addTab("Julian Monsalve", pnlJugador2);

        getContentPane().add(tpJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 560, 280));

        btnConteo.setBackground(new java.awt.Color(102, 255, 0));
        btnConteo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnConteo.setForeground(new java.awt.Color(0, 0, 0));
        btnConteo.setText("Conteo");
        btnConteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConteoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConteo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRepartirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepartirActionPerformed
        jugador1.repartir();
        jugador2.repartir();

        jugador1.mostrar(pnlJugador1);
        jugador2.mostrar(pnlJugador2);
    }//GEN-LAST:event_btnRepartirActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        int pestaña = tpJugadores.getSelectedIndex();
        String mensaje = "";
        switch (pestaña) {
            case 0 ->
                mensaje = jugador1.getGrupos() + jugador1.getEscaleras();
            case 1 ->
                mensaje = jugador2.getGrupos() + jugador2.getEscaleras();
        }
        JOptionPane.showMessageDialog(null, mensaje);
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnConteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConteoActionPerformed
        int pestaña = tpJugadores.getSelectedIndex();
        int mensaje = 0;
        switch (pestaña) {
            case 0 ->
                mensaje = jugador1.calcularPuntaje();
            case 1 ->
                mensaje = jugador2.calcularPuntaje();
        }
        JOptionPane.showMessageDialog(null, "La suma de los numeros restantes es:\n " + mensaje);
//        List<Carta> Nocarta = new ArrayList<>();
//        int acomuladorFinal = 0;
//        int acomulador = 0;
//        for (Carta c : Nocarta) {
//                if (String.valueOf(c.getNombreCarta().ordinal()) == jugador1.getGrupos()) {
//                    acomulador += acomulador;
//                }
//                else {
//                    acomuladorFinal += acomulador + c.getNombreCarta().ordinal();
//                }
//            }
//        JOptionPane.showMessageDialog(null, String.valueOf(acomuladorFinal));
//        
//        jugador1.repartir();
//        String mensaje = ";";
//        switch (pestaña){
//            case 0 ->
//                mensaje = String.valueOf(jugador1.getNoEscalera());
//        }
//        String grupos1 = jugador1.getGrupos();
//        String escaleras1 = jugador1.getEscaleras();
//
//        jugador2.repartir();
//        String grupos2 = jugador2.getGrupos();
//        String escaleras2 = jugador2.getEscaleras();
//        int AcomJug1 = jugador1.getConteo(jugador1, grupos1, escaleras1);
//        int AcomJug2 = jugador2.getConteo(jugador1, grupos2, escaleras2);
//        JOptionPane.showMessageDialog(null, " la suma de las cartas restantes es: " + AcomJug1);
////        String mensaje = "";
////        int acmulador = 0;
////        int i;
////        String grupos1 = jugador1.getGrupos();
////        String escaleras1 = jugador1.getEscaleras();
////        String grupos2 = jugador2.getGrupos();
////        String escaleras2 = jugador2.getEscaleras();
////        switch (pestaña) {
////            case 0 ->
////                if(grupos1.equals("no hay grupos") && escaleras1.equals("no hay escaleras")){
////                   
////                }
//
//        }
    }//GEN-LAST:event_btnConteoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConteo;
    private javax.swing.JButton btnRepartir;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JPanel pnlJugador1;
    private javax.swing.JPanel pnlJugador2;
    private javax.swing.JTabbedPane tpJugadores;
    // End of variables declaration//GEN-END:variables
}
